apiVersion: v1
kind: Service
metadata:
    name: query-frontend
spec:
  ports:
  - name: query-frontend-prom-metrics
    port: 3100
    targetPort: 3100
  - name: tempo-query-jaeger-ui
    port: 16686
    targetPort: 16686
  - name: tempo-querier
    port: 9095
    targetPort: 9095
  selector:
    app: query-frontend
    name: query-frontend
